[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
